name: textly
description: Frontend textly app for web/desktop/mobile
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.1
  sentry_flutter: ^7.4.0
  stack_trace: ^1.11.0
  shared_preferences: ^2.0.20
  jwt_decoder: ^2.0.1
  platform_info: ^3.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.17.0
  l: ^3.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  textly_core:
    git:
      url: git@github.com:serezhia/textly_core.git
      ref: dev
  fresh:
    path: ./packages/fresh
  textly_ui:
    path: ./packages/textly_ui
  go_router:
    path: ./packages/go_router
  dio: ^5.1.1
  email_validator: ^2.1.17
  pin_code_fields: ^7.4.0

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Noto Emoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf

    - family: TT Norms Pro
      fonts:
        - asset: assets/fonts/ttnorms/TTNormsPro-Regular.ttf

        - asset: assets/fonts/ttnorms/TTNormsPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/ttnorms/TTNormsPro-Bold.ttf
          weight: 600
        - asset: assets/fonts/ttnorms/TTNormsPro-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/ttnorms/TTNormsPro-Black.ttf
          weight: 800
        - asset: assets/fonts/ttnorms/TTNormsPro-ExtraBlack.ttf
          weight: 900
