name: fresh
description: Fresh lib for refresh tokens
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dio: ^5.1.1
  textly_core:
    git:
      url: git@github.com:serezhia/textly_core.git
      ref: dev

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
